language: node_js
node_js:
  - stable
env:
  global:
    - GIT_DEPLOY_USERNAME="Travis CI"
    - GIT_DEPLOY_EMAIL=filip.dupanovic@gmail.com
    - GIT_DEPLOY_DIR=srv
    - GIT_DEPLOY_BRANCH=gh-pages
    - GIT_DEPLOY_REPO=git@github.com:langri-sha/langri-sha.github.io.git

before_deploy:
- |
    curl \
    -L https://github.com/X1011/git-directory-deploy/raw/master/deploy.sh \
    --create-dirs -o local/deploy.sh
    chmod +x local/deploy.sh

    openssl aes-256-cbc \
      -K $encrypted_e90277111077_key \
      -iv $encrypted_e90277111077_iv \
      -in share/deploy_key.enc -out local/deploy_key -d
    chmod 600 local/deploy_key
    eval `ssh-agent -s`
    ssh-add local/deploy_key

    npm run build

deploy:
  provider: script
  script: local/deploy.sh
  skip_cleanup: true
  on:
    branch: master
