language: node_js
node_js:
  - stable
env:
  global:
    - GIT_DEPLOY_USERNAME="Travis CI"
    - GIT_DEPLOY_EMAIL=filip.dupanovic@gmail.com
    - GIT_DEPLOY_DIR=srv
    - GIT_DEPLOY_BRANCH=gh-pages
    - GIT_DEPLOY_REPO=git@github.com:langri-sha/langri-sha.github.io.git

before_deploy:
- |
    openssl aes-256-cbc \
      -K $encrypted_e90277111077_key \
      -iv $encrypted_e90277111077_iv \
      -in share/deploy_key.enc -out deploy_key -d
    chmod 600 deploy_key
    eval `ssh-agent -s`
    ssh-add deploy_key

    npm run build

    wget https://github.com/X1011/git-directory-deploy/raw/master/deploy.sh
    chmod +x deploy.sh
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
