ignore = [
  "**/node_modules",
  "**/dist",
  "**/.next",
  "**/.tsbuild",
  "**/*.tsbuildinfo",
  "**/.terraform",
  "**/target",
]

[modules.ci]
source = "github.com/langri-sha/dagger/ci@ci/v0.1.0"

[modules.terraform]
source = "github.com/langri-sha/dagger/terraform@terraform/v0.1.0"

[modules.terraform.settings]
rootModule = "terraform/web"

[modules.eslint]
source = "dagger.io/js/eslint"

[modules.eslint.settings]
packageManager = "pnpm"
baseImageAddress = "node:24-slim"

[modules.prettier]
source = "dagger.io/js/prettier"

[modules.prettier.settings]
packageManager = "pnpm"
baseImageAddress = "node:24-slim"

[modules.vitest]
source = "dagger.io/js/vitest"

[modules.vitest.settings]
packageManager = "pnpm"
baseImageAddress = "node:24-slim"
