x-user-args: &user-args
  uid: ${UID:-1000}

x-terraform-env: &terraform-env
  GITHUB_TOKEN: '${GITHUB_PAT:-${X_GITHUB_PAT:-${GITHUB_TOKEN:-}}}'

x-gcloud-volume: &gcloud-volume
  read_only: true
  source: ~/.config/gcloud
  target: /home/terraform/.config/gcloud
  type: bind

x-terraform-credentials-volume: &terraform-credentials-volume
  read_only: true
  source: ~/.terraform.d
  target: /home/terraform/.terraform.d
  type: bind

x-workspace-volume: &workspace-volume
  source: .
  target: /workspace
  type: bind
  consistency: delegated

x-google-dns: &google-dns
  dns:
    - 8.8.8.8
    - 8.8.4.4

x-terraform-svc: &terraform-svc
  image: gcr.io/${PROJECT_ID:-local}/terraform
  entrypoint: ['terraform']
  command: ['init']
  init: true
  volumes:
    - *gcloud-volume
    - *terraform-credentials-volume
    - *workspace-volume
  environment:
    <<: *terraform-env

x-pnpm-svc: &pnpm-svc
  image: gcr.io/${PROJECT_ID:-local}/pnpm
  init: true
  entrypoint: ['pnpm']
  working_dir: /workspace
  volumes:
    - *workspace-volume

services:
  terraform:
    <<: [*terraform-svc, *google-dns]
    build:
      context: ./terraform
      cache_from:
        - gcr.io/${PROJECT_ID:-local}/terraform
      args:
        <<: *user-args
    entrypoint: ash
    command: []

  terraform-web:
    <<: [*terraform-svc, *google-dns]
    working_dir: /workspace/terraform/web
    depends_on:
      - terraform

  pnpm:
    <<: [*pnpm-svc, *google-dns]
    build:
      dockerfile: ./docker/pnpm/Dockerfile
      context: .
      cache_from:
        - gcr.io/${PROJECT_ID:-local}/pnpm
      args:
        <<: *user-args

  server:
    <<: [*pnpm-svc, *google-dns]
    command: ['start', '--http', '--host=0.0.0.0', '--allowed-hosts=localhost']
    ports:
      - '8080:8080'
