x-alpine-args: &alpine-args
  alpine_version: '3.16'

x-kubernetes-args: &kubernetes-args
  kubernetes_version: '1.24.3'

x-node-args: &node-args
  node_version: '18.7.0'
  glibc_version: '2.33-r0'

x-terraform-args: &terraform-args
  google_cloud_sdk_version: '395.0.0'
  terraform_version: '1.2.6'

x-user-args: &user-args
  uid: ${UID:-1000}

x-terraform-env: &terraform-env
  TF_CLI_CONFIG_FILE: '${TF_CLI_CONFIG_FILE:-/workspace/.terraformrc}'
  TF_VAR_admin_members: '${admin_members:-}'
  TF_VAR_billing_account: '${billing_account:-}'
  TF_VAR_billing_members: '${billing_members:-}'
  TF_VAR_domain: '${domain:-}'
  TF_VAR_location: '${location:-}'
  TF_VAR_mx_records: '${mx_records:-}'
  TF_VAR_region: '${region:-}'
  TF_VAR_site_verifications: '${site_verifications:-}'
  TF_VAR_zone: '${zone:-}'

x-workspace-volume: &workspace-volume
  source: .
  target: /workspace
  type: bind
  consistency: delegated

x-terraform-svc: &terraform-svc
  image: gcr.io/${PROJECT_ID:-local}/terraform
  entrypoint: ['terraform']
  command: ['init']
  init: true
  volumes:
    - *workspace-volume
  environment:
    <<: *terraform-env

x-yarn-svc: &yarn-svc
  image: gcr.io/${PROJECT_ID:-local}/yarn
  init: true
  entrypoint: ['yarn']
  working_dir: /workspace
  volumes:
    - *workspace-volume

services:
  terraform:
    <<: *terraform-svc
    build:
      context: ./terraform
      cache_from:
        - gcr.io/${PROJECT_ID:-local}/terraform
      args:
        <<: [*alpine-args, *kubernetes-args, *terraform-args, *user-args]
    entrypoint: ash
    command: []

  terraform-org:
    <<: *terraform-svc
    working_dir: /workspace/terraform/org
    depends_on:
      - terraform

  terraform-web:
    <<: *terraform-svc
    working_dir: /workspace/terraform/web
    depends_on:
      - terraform

  yarn:
    <<: *yarn-svc
    build:
      context: .
      cache_from:
        - gcr.io/${PROJECT_ID:-local}/yarn
      args:
        <<: [*alpine-args, *node-args, *user-args]

  server:
    <<: *yarn-svc
    command: ['start', '--http', '--host=0.0.0.0', '--allowed-hosts=localhost']
    ports:
      - '8080:8080'
