# Build configuration overview: https://cloud.google.com/cloud-build/docs/build-config
# Cloud builders: https://cloud.google.com/cloud-build/docs/cloud-builders

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Configure permissions'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        chown -R 1000 /workspace/terraform/
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: ['compose', 'build', 'terraform']
    waitFor: ['-']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Initialize org configuration'
    dir: /workspace/terraform/org
    args: ['init', '-backend=false']
    waitFor: ['Configure permissions', 'Build image']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Validate org configuration'
    dir: /workspace/terraform/org
    args: ['validate']
    waitFor: ['Initialize org configuration']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Format org configuration'
    dir: /workspace/terraform/org
    args: ['fmt', '-recursive', '-diff', '-check']
    waitFor: ['Validate org configuration']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Initialize web configuration'
    dir: /workspace/terraform/web
    args: ['init', '-backend=false']
    waitFor: ['Configure permissions', 'Build image']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Validate web configuration'
    dir: /workspace/terraform/web
    args: ['validate']
    waitFor: ['Initialize web configuration']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Format web configuration'
    dir: /workspace/terraform/web
    args: ['fmt', '-recursive', '-diff', '-check']
    waitFor: ['Validate web configuration']

options:
  env:
    - PROJECT_ID=$PROJECT_ID

  volumes:
    - name: share
      path: /var/share
