# Build configuration overview: https://cloud.google.com/cloud-build/docs/build-config
# Cloud builders: https://cloud.google.com/cloud-build/docs/cloud-builders

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Configure permissions'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        chown -R 1000 /workspace/terraform/
    waitFor: ['-']

  - name: 'gcr.io/kaniko-project/executor:debug'
    id: 'Build Terraform image'
    entrypoint: /busybox/sh
    args:
      - -c
      - |
        executor \
          --build-arg="alpine_version=$$(eval $$ALPINE_VERSION)" \
          --build-arg="google_cloud_sdk_version=$$(eval $$GOOGLE_CLOUD_SDK_VERSION)" \
          --build-arg="terraform_version=$$(eval $$TERRAFORM_VERSION)" \
          --build-arg="uid=1000" \
          --destination=gcr.io/$PROJECT_ID/terraform \
          --context=/workspace/terraform/ \
          --cache=true
    waitFor: ['-']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Initialize org configuration'
    dir: /workspace/terraform/org
    args: ['init', '-backend=false']
    waitFor: ['Configure permissions', 'Build Terraform image']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Validate org configuration'
    dir: /workspace/terraform/org
    args: ['validate']
    waitFor: ['Initialize org configuration']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Format org configuration'
    dir: /workspace/terraform/org
    args: ['fmt', '-recursive', '-diff', '-check']
    waitFor: ['Validate org configuration']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Initialize web configuration'
    dir: /workspace/terraform/web
    args: ['init', '-backend=false']
    waitFor: ['Configure permissions', 'Build Terraform image']

  - name: 'gcr.io/$PROJECT_ID/terraform'
    id: 'Validate web configuration'
    dir: /workspace/terraform/web
    args: ['validate']
    waitFor: ['Initialize web configuration']

options:
  env:
    - ALPINE_VERSION=cat docker-compose.yml | grep alpine_version | cut -d ':' -f 2 | xargs
    - GOOGLE_CLOUD_SDK_VERSION=cat docker-compose.yml | grep google_cloud_sdk_version | cut -d ':' -f 2 | xargs
    - TERRAFORM_VERSION=cat docker-compose.yml | grep terraform_version | cut -d ':' -f 2 | xargs
