name: Terraform
description: |-
  Checks the current Terraform configuration to ensure the dependencies,
  formatting and resources are all valid. Will use the preferred Terraform
  version, if configured in the sources.

  Runs in the current working directory.

runs:
  using: composite

  steps:
    - name: Install ripgrep
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y ripgrep
