name: Terraform
description: |-
  Checks the current Terraform configuration to ensure the dependencies,
  formatting and resources are all valid. Will use the preferred Terraform
  version, if configured in the sources.

  Runs in the current working directory.

runs:
  using: composite

  steps:
    - name: Install ripgrep
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y ripgrep

    - name: Get version
      id: version
      shell: bash
      run: |
        echo "terraform-version=$(rg "required_version = \"(\d+\.\d+\.\d+)\"" -t tf -or '$1' --no-filename | tail -1)" >> $GITHUB_OUTPUT

    - name: Warn missing version
      if: steps.version.outputs.terraform-version == ''
      shell: bash
      run: |
        echo "::warning::Missing Terraform version"

    - name: Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.version.outputs.terraform-version || 'latest' }}

    - name: Initialize
      shell: bash
      run: terraform init -backend=false

    - name: Fail on lockfile changes
      shell: bash
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo 'Terraform lockfile changed.'
          echo 'Did you remember to run `terraform init` and commit changes to `.terraform.lock.hcl`?'
          git diff
          exit 1
        fi

    - name: Format
      shell: bash
      run: terraform fmt -recursive -check
