import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

import { fonts } from '../src/index.ts'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')
const dist = path.join(root, 'dist')

await rm(dist, { recursive: true, force: true })
await mkdir(dist, { recursive: true })

const entries = []

for (const [name, font] of Object.entries(fonts)) {
  const woff2 = await readFile(path.join(root, font.output))
  await writeFile(path.join(dist, path.basename(font.output)), woff2)

  const dataUri = `data:font/woff2;base64,${woff2.toString('base64')}`
  const fontFace =
    `@font-face{` +
    `font-family:'${font.family}';` +
    `src:url(${dataUri}) format('woff2');` +
    `font-weight:${font.weight};` +
    `font-style:${font.style};` +
    `font-display:swap` +
    `}`

  entries.push({ name, family: font.family, fontFace })
}

const banner =
  '// Generated by `pnpm --filter @langri-sha/fonts build`. Do not edit.\n\n'

const js =
  banner +
  entries
    .map(
      ({ name, family, fontFace }) =>
        `export const ${name} = {\n` +
        `  family: ${JSON.stringify(family)},\n` +
        `  fontFace: ${JSON.stringify(fontFace)},\n` +
        `}\n`,
    )
    .join('\n') +
  `\nexport const fontFaces = [${entries.map(({ name }) => name).join(', ')}]` +
  `\n  .map((font) => font.fontFace)\n  .join('')\n`

const dts =
  banner +
  `export interface Font {\n` +
  `  /** The \`font-family\` the subset is published under. */\n` +
  `  family: string\n` +
  `  /** A self-contained \`@font-face\` rule with the woff2 inlined as a data URI. */\n` +
  `  fontFace: string\n` +
  `}\n\n` +
  entries.map(({ name }) => `export declare const ${name}: Font\n`).join('') +
  `\nexport declare const fontFaces: string\n`

await writeFile(path.join(dist, 'index.js'), js)
await writeFile(path.join(dist, 'index.d.ts'), dts)

for (const { name, fontFace } of entries) {
  console.log(`${name}: dist/ + ${fontFace.length}-byte inline @font-face`)
}
