declare module 'eslint-plugin-import'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-react/configs/jsx-runtime.js'
declare module 'eslint-plugin-react/configs/recommended.js'
declare module 'eslint-plugin-unicorn'
