name: PNPM
description: |-
  Configures PNPM and Node.js, and installs dependencies.

runs:
  using: composite

  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        run_install: false
