name: Packages

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup PNPM
        uses: ./.github/actions/pnpm
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@langri-sha'

      - name: Configure Git user
        run: |
          git config user.name "Filip Dupanović"
          git config user.email "filip.dupanovic@gmail.com"

      - name: Build composite projects
        run: pnpm tsc --build .

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx beachball@2.43.1 publish \
            --access public \
            --message "feat(beachball): Publish packages" \
            --new \
            --yes
