name: Release

on:
  workflow_dispatch:

jobs:
  packages:
    name: Packages
    uses: langri-sha/github/.github/workflows/packages.yml@v0.5.2
    with:
      environment: release
      scope: '@langri-sha'
    secrets: inherit
