name: Release

on:
  workflow_dispatch:

jobs:
  packages:
    name: Packages
    permissions:
      id-token: write
      contents: read
    uses: langri-sha/github/.github/workflows/packages.yml@v0.8.0
    with:
      environment: release
      scope: '@langri-sha'
    secrets: inherit
