name: Renovate Post-Upgrade

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  post-upgrade:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'renovate-bot' || github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm

      - name: Update Jest snapshots
        run: pnpm jest --updateSnapshot --passWithNoTests

      - name: Create Beachball changes
        run: |
          pnpm beachball change \
            --message "chore(deps): ${{ github.event.pull_request.title }}" \
            --no-commit \
            --type patch \
            --yes
