name: Renovate Post-Upgrade

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  post-upgrade:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'renovate-bot' || github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm
