name: Renovate Post-Upgrade

on:
  pull_request:

jobs:
  post-upgrade:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]' }}
    outputs:
      has-changes: ${{ steps.git-changes.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm

      - name: Update Jest snapshots
        run: pnpm jest --updateSnapshot --passWithNoTests

      - name: Create Beachball changes
        run: |
          pnpm beachball change \
            --message "chore(deps): ${{ github.event.pull_request.title }}" \
            --no-commit \
            --type patch \
            --yes

      - name: Check for Git changes
        id: git-changes
        run: |
          if git status --porcelain; then
            echo "has-changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create patch
        run: |
          git add -A
          git diff --cached > .diff.patch

      - name: Upload diff
        uses: actions/upload-artifact@v4
        if: ${{ steps.git-changes.outputs.has-changes }}
        with:
          path: .diff.patch

  commit-upgrade-changes:
    runs-on: ubuntu-latest
    if: ${{ needs.post-upgrade.outputs.has-changes }}
    needs: [post-upgrade]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download diff
        uses: actions/download-artifact@v4

      - name: Apply diff
        run: |
          git apply .diff.patch
          git add .
          git commit -m "chore(deps): Apply upgrade changes"
          git push origin HEAD
