name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform.yml'
      - '*.tf'
      - '*.lock.hcl'
  pull_request:
    paths:
      - '.github/workflows/terraform.yml'
      - '*.tf'
      - '*.lock.hcl'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - terraform/web
          - terraform/org

    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
