name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform.yml'
      - '*.tf'
      - '*.lock.hcl'
  pull_request:
    paths:
      - '.github/workflows/terraform.yml'
      - '*.tf'
      - '*.lock.hcl'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - terraform/web
          - terraform/org

    steps:
      - run: echo "OK"
