name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform.yml'
      - '*.tf'
      - '*.lock.hcl'
  pull_request:
    paths:
      - '.github/workflows/terraform.yml'
      - '*.tf'
      - '*.lock.hcl'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - terraform/web
          - terraform/org

    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Get version
        id: version
        run: |
          echo "terraform-version=$(rg "required_version = \"(\d+\.\d+\.\d+)\"" -t tf -or '$1' --no-filename | tail -1)" >> $GITHUB_OUTPUT

      - name: Warn missing version
        if: steps.version.outputs.terraform-version == ''
        run: |
          echo "::warning::Missing Terraform version"

      - name: Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.version.outputs.terraform-version || 'latest' }}

      - name: Initialize
        run: terraform init -backend=false
