name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - *.tf
      - *.lock.hcl
  pull_request:
    paths:
      - *.tf
      - *.lock.hcl

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - run: echo "OK"
