name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"
      - "*.lock.hcl"
  pull_request:
    paths:
      - "*.tf"
      - "*.lock.hcl"

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - terraform/web
          - terraform/org

    defaults:
      run:
        working-directory: ${matrix.working-directory}

    steps:
      - run: echo "OK"
