name: Web Deploy

on:
  workflow_run:
    workflows:
      - Workspace
      - Web

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Add status check
        uses: haya14busa/action-workflow_run-status@v1

      - name: Checkout
        uses: actions/checkout@v4
