name: Web

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm

      - name: Build
        run: pnpm build

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: apps/web/dist
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    environment: ${{ github.event_name == 'release' && 'production' || 'preview' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud Platform
        uses: ./.github/actions/google-cloud-platform
        with:
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          setup_gcloud: true
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: dist/web

      - name: Configure environment
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "ASSETS_BUCKET=gs://${{ vars.ASSETS_BUCKET }}/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            echo "ASSETS_URL=${{ vars.ASSETS_URL }}/${{ github.event.pull_request.number }}" >> $$GITHUB_ENV
            echo "BUCKET=gs://${{ vars.BUCKET }}/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            echo "URL=${{ vars.URL }}/${{ github.event.pull_request.number }}" >> $$GITHUB_ENV
          else
            echo "ASSETS_BUCKET=gs://${{ vars.ASSETS_BUCKET }}"  >> $GITHUB_ENV
            echo "ASSETS_URL=${{ vars.ASSETS_URL }}"  >> $GITHUB_ENV
            echo "BUCKET=gs://${{ vars.BUCKET }}" >> $GITHUB_ENV
            echo "URL=${{ vars.URL }}" >> $GITHUB_ENV
          fi

      - name: Publish
        run: |
          GZIP_TYPES=css,eot,html,js,json,otf,svg,ttf,txt

          gsutil -u ${{ vars.EDGE_PROJECT_ID }} -qm rsync -r -j $GZIP_TYPES -x gz dist/web ${{ env.BUCKET }}
