name: Web

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `HEAD`
        uses: actions/checkout@v2
      - name: Use latest stable Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn dependencies
        run: yarn install
      - name: Fail on lockfile changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Yarn lockfile changed, failing tests!"
            echo "Did you remember to run `yarn install` and commit changes to `yarn.lock`?"
            git diff
            exit 1
          fi

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `HEAD`
        uses: actions/checkout@v2
      - name: Use latest stable Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn dependencies
        run: yarn install
      - name: Build
        run: yarn build
