name: Web

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm

      - name: Build
        run: pnpm build

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: apps/web/dist
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud Platform
        uses: ./.github/actions/google-cloud-platform
        with:
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          setup_gcloud: true
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: dist/web
