name: Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    uses: langri-sha/github/.github/workflows/check.yml@v0.7.2
    with:
      beachball: true
      eslint: true
      packages: true
      prettier: true
      projen: true
      typescript: true
      vitest: true
