name: Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  workspace:
    uses: langri-sha/github/.github/workflows/workspace.yml@v0.4.0
    with:
      beachball: true
      eslint: true
      packages: true
      prettier: true
      projen: true
      typescript: true
      vitest: true
