name: Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm

      - name: ESLint
        run: pnpm eslint .

      - name: Prettier
        run: pnpm prettier --check .

      - name: TypeScript
        run: pnpm tsc --build .

      - name: Beachball
        if: github.event_name == 'pull_request'
        run: |
          pnpm beachball check ||
          (
            echo "::error::Beachballchanges detected. Run 'pnpm beachball change' and commit the changes.";
            exit 1
          )

      - name: Sort packages
        run: |
          pnpx sort-package-json --check \
            ./apps/*/package.json \
            ./packages/*/package.json \
            package.json

      - name: Check packages
        run: |
          pnpm -r exec npm pkg fix

          if [[ $(git status --porcelain) ]]; then
            echo '::error::Some packages need fixing.'
            git diff
            exit 1
          fi

      - name: Check projen configuration
        run: |
          pnpx projen

          if [[ $(git status --porcelain) ]]; then
            echo '::error::Some projen changes haven not been appplied. Run `pnpx projen`.'
            git diff
            exit 1
          fi

  jest:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm

      - name: Jest
        run: pnpm jest --passWithNoTests
